### ISSUE TITLE
Biome Builder Has No Settings

### ISSUE THREAD

**Issue by TheDarkula** [biome-sh/biome#12]
In the habitat builder, you can go to https://bldr.habitat.sh/#/origins/name-goes-here/settings and change the visibility of the origin's packages.

There is no settings tab in the biome builder.

**Comment by jsirex** [comment]
I have the following settings for the frontend component:
``` toml
app_url                   = "https://bldr.example.com"
environment               = "production"
hosted                    = false
enable_builder            = true
source_code_url           = "https://github.com/biome-sh/biome"
# TODO: change status url for the builder
status_url                = "https://status.bldr.example.com/"

tutorials_url             = "https://www.habitat.sh/learn"
use_gravatar              = true
www_url                   = "https://www.habitat.sh"

[analytics]
company_id                = ""
company_name              = ""
enabled                   = false
write_key                 = ""

[oauth]
authorize_url             = "https://gitlab.example.com/oauth/authorize"
client_id                 = "{{ builder_api_proxy_secret.oauth_client_id }}"
provider                  = "gitlab"
redirect_url              = "https://bldr.example.com/"
signup_url                = "https://gitlab.example.com/"

[server]
listen_tls                = true
cert_file                 = "_.example.com.crt"
cert_key_file             = "_.example.com.key"
ssl_protocols             = "TLSv1.2 TLSv1.3"

```

I saw this issue and forgot how exactly fix it. Probably `hosted = false` or `enable_builder = true` show the tab.
Also sometimes there is issue with origins' ownership so no settings tab.
